default: &default
  adapter: postgresql
  encoding: unicode
  # username: postgres
  # password: postgres
  # host: 127.0.0.1
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_scheduler_development

test:
  <<: *default
  database: task_scheduler_test

production:
  <<: *default
  database: task_scheduler_production
  username: task_scheduler
  password: <%= ENV['TASK_SCHEDULER_DATABASE_PASSWORD'] %>
